services:
  mongo:
    image: mongo:latest
    container_name: mongo_railway
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGODB_DB: ${MONGODB_DB}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq_railway
    ports:
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}

  reciver:
    build:
      context: ./modules/reciver
      dockerfile: Dockerfile
      args:
        MONGODB_DB: ${MONGODB_DB}
        MONGODB_USER: ${MONGODB_USER}
        MONGODB_PASSWORD: ${MONGODB_PASSWORD}
        MONGODB_URI: ${MONGODB_URI}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
        RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
        RABBITMQ_URI: ${RABBITMQ_URI}
    environment:
      MONGOOB_DB: ${MONGODB_DB}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_URI: ${MONGODB_URI}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_URI: ${RABBITMQ_URI}
    depends_on:
      - rabbitmq
      - mongo

  gateway:
    build:
      context: ./modules/gateway
      dockerfile: Dockerfile
      args:
        MONGODB_DB: ${MONGODB_DB}
        MONGODB_USER: ${MONGODB_USER}
        MONGODB_PASSWORD: ${MONGODB_PASSWORD}
        MONGODB_URI: ${MONGODB_URI}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
        RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
        RABBITMQ_URI: ${RABBITMQ_URI}
    environment:
      MONGOOB_DB: ${MONGODB_DB}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_URI: ${MONGODB_URI}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_URI: ${RABBITMQ_URI}
    depends_on:
      - rabbitmq
      - mongo
    ports:
      - 3000:3000
